on: [ push, pull_request ]
name: Test
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php: [ '7.4', '8.0' , '8.1' ]
        composer-options: [ '', '--prefer-lowest' ]
        composer-versions: [ 'composer:v2' ]
      fail-fast: true
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.composer-versions }}
          extensions: xdebug, mbstring, posix
      - name: Check Versions
        run: |
          php -v
          php -m
          composer --version
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        if: matrix.php-versions != '8.1'
        run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}
      - name: Install dependencies (Ignore platform)
        if: matrix.php-versions == '8.1'
        run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }} --ignore-platform-req=php
      - name: Set git variables
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Run the tests
        run: php vendor/bin/grumphp run --no-interaction
        continue-on-error: ${{ matrix.php == '8.1' && matrix.composer-options == '--prefer-lowest' }}
